services:
  grpc-postgres:
    image: postgres
    container_name: grpc-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - weather_postgres_data:/var/lib/postgresql


volumes:
  weather_postgres_data: